name: CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  backend:
    name: Backend Maven Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build and Test with Maven
        run: |
          cd RuoYi-Vue-Plus
          mvn clean test

  frontend:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd plus-ui
          npm install --registry=https://registry.npmmirror.com
      - name: Run build
        run: |
          cd plus-ui
          npm run build:prod
      # 如有前端测试脚本可取消注释
      # - name: Run frontend tests
      #   run: |
      #     cd plus-ui
      #     npm run test
